[package]
name = "sgx"
version = "1.0.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
cc = "1.0"

[dependencies]
vpma-verified = { path = "../verified" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hmac = { version = "0.12", default-features = false }
sha2 = { version = "0.10", default-features = false }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
ed25519-dalek = { version = "2.0", default-features = false, features = ["alloc"] }
mbedtls = { version = "0.12", features = ["std", "ssl", "x509", "rdrand"], optional = true }

[target.'cfg(target_env = "sgx")'.dependencies]
rdrand = "0.8"
sgx-isa = "0.4"
aes-gcm = { version = "0.10", default-features = false, features = ["aes", "alloc"] }

[features]
use_mbedtls = ["mbedtls"]

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

[[bin]]
name = "sgx"
path = "src/main.rs"

[[bin]]
name = "sgx_simple"
path = "src/main_simple.rs"

[[bin]]
name = "test_enclave"
path = "src/bin/test_enclave.rs"
