[package]
name = "scaphandre-loader"
version = "1.0.0"
authors = ["Benoit Petit <bpetit@hubblo.org>"]
edition = "2021"
license = "Apache-2.0"
description = "Minimal loader for secure-scaphandre (measured by IMA, stable hash)"

[dependencies]
clap = { version = "4.2", features = ["derive"] }

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
strip = true
panic = "abort"
